name: Kaniko Build / Push to Dockerhub
on: push
jobs:
  latest: 
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: alpine
    steps:
      - uses: actions/checkout@master
      - name: Kaniko build
        uses: aevea/action-kaniko@master
        with:
          image: netlify-cli
          extra_args: --build-arg NODE_VERSION=${{ env.NODE_VERSION}} --build-arg NETLIFY_CLI_VERSION=latest
